@echo off
setlocal enabledelayedexpansion

set "ROOT=%~dp0"
set "TARGET=%ROOT%server_ip.txt"
set "CONFIG=%ROOT%config.php"

set /p NEW_IP=Nhap IP moi cua may chu (vi du 192.168.1.50): 

if not defined NEW_IP (
    echo Khong nhap IP. Thoat.
    exit /b 1
)

> "%TARGET%" echo %NEW_IP%

echo Da luu IP moi vao %TARGET%

echo Cap nhat file config.php...

if exist "%CONFIG%" (
    powershell -NoProfile -Command "$path = '%CONFIG%'; $content = Get-Content $path -Raw; $content = $content -replace 'server_ip.txt', 'server_ip.txt'; Set-Content -Path $path -Value $content -Encoding UTF8;"
)

(
    echo // Auto-generated by update_server_ip.bat
    echo <?php
    echo $server_ip = '%NEW_IP%';
    echo ?>
) > "%ROOT%server_config.php"

echo Hoan thanh. Ban co the chay Start.bat de khoi dong lai he thong.
pause
